CREATE TABLE `mbk_orders` (
  `ORDERID` varchar(35) COLLATE utf8_bin NOT NULL COMMENT '订单ID',
  `USERID` varchar(35) COLLATE utf8_bin DEFAULT NULL,
  `BIKEID` varchar(11) COLLATE utf8_bin DEFAULT NULL,
  `STARTPOSITIONX` decimal(11,8) DEFAULT NULL COMMENT '开始位置经度',
  `STARTPOSITIONY` decimal(11,8) DEFAULT NULL COMMENT '开始位置纬度',
  `STARTTIME` datetime DEFAULT NULL COMMENT '开始时间',
  `TOTALDISTANCE` int(11) DEFAULT NULL COMMENT '骑行距离,默认单位是M',
  `CALORIE` decimal(11,8) DEFAULT NULL COMMENT '消耗的卡路里数',
  `TOTALDURATION` int(20) DEFAULT NULL COMMENT '骑行时间',
  `ENDTIME` datetime DEFAULT '1999-12-12 00:00:02' COMMENT '结束时间',
  `ENDPOSITIONX` decimal(11,8) DEFAULT NULL COMMENT '结束经度',
  `ENDPOSITIONY` decimal(11,8) DEFAULT NULL COMMENT '结束纬度',
  `TOTALFEE` decimal(11,5) DEFAULT NULL COMMENT '费用金额,默认单位是元',
  `RENTSTATUS` char(1) COLLATE utf8_bin DEFAULT NULL COMMENT '租车状态,0：骑行中RN1：中途锁车RN2：未付款RN3：已经结束',
  `LOCKMILISECONDS` int(21) DEFAULT NULL COMMENT '中途停车时长',
  `TS` timestamp NULL DEFAULT '1999-12-12 16:00:02' COMMENT '时间戳',
  `ISDELETE` char(1) COLLATE utf8_bin DEFAULT '0' COMMENT '是否删除 0 未删除 1 删除 默认是0',
  `TIMELINESS` char(1) COLLATE utf8_bin DEFAULT '0' COMMENT '是否是否使用优惠券 0 使用 1 未使用',
  `PROGRESS` tinyint(1) NOT NULL DEFAULT '0' COMMENT '注册进度 默认 “0”',
  `CITYCODE` varchar(8) COLLATE utf8_bin DEFAULT NULL COMMENT '城市编号 国内采用城市区号 国外采用百度地图的城市编号',
  `AREACODE` varchar(8) COLLATE utf8_bin DEFAULT NULL,
  `BIKETYPE` int(2) DEFAULT NULL,
  `COUNTRY_CODE` varchar(4) COLLATE utf8_bin DEFAULT NULL COMMENT '国家代码 详见字典表country',
  `CURRENCY` int(8) DEFAULT NULL COMMENT '货币类型 0-CNY-人民币 1-SGD-新加坡元 2-USD-美元 3-GBP-英镑 4-MYR-马来西亚林吉特\n 5-TWD-新台币 6-JPY-日元 7-EUR-欧元 8-DKK-丹麦克朗 9-THB-泰铢 10-SEK-瑞典克朗\n 11-KRW-韩元 12-INR-印度卢比 13-CAD-加元',
  `OS_PLATFORM` int(4) DEFAULT NULL COMMENT '平台类型 0-ios 1-android 2-wap 3-weixin-ios 4-weixin-android 5-baidu-ios 6-baidu-android\n 7-amap-ios 8-amap-android 9-tencent-ios 10-tencent-android',
  `OS_VERSION` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '平台版本',
  `SOURCE` int(4) DEFAULT NULL COMMENT '注册渠道 1-iOS 2-安卓 3-小程序iOS 4-小程序安卓 5-优惠券 6-裂变红包 7-宝箱车',
  `SUB_SOURCE` varchar(40) COLLATE utf8_bin DEFAULT NULL COMMENT '注册子渠道',
  `APP_VERSION` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'app版本号',
  `DEDUCTION_FEE` int(11) DEFAULT NULL COMMENT '用户标记订单减免金额,单位分',
  `EXTEND1` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展预留字段1',
  `EXTEND2` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展预留字段2',
  PRIMARY KEY (`ORDERID`),
  KEY `MBK_ORDER_USER_FK` (`USERID`),
  KEY `MBK_ORDER_BIKE_FK` (`BIKEID`),
  KEY `TS_INDEX` (`TS`),
  KEY `ENDTIME_INDEX` (`ENDTIME`),
  KEY `IX_STARTTIME` (`STARTTIME`)
);
